# Generated by Django 4.2.4 on 2023-08-24 10:49

import base_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null= True, blank=True),
            preserve_default=False,
        ),
    ]
